"""empty message

Revision ID: 1300e94cf5cc
Revises: 3ee40f5fdc1f
Create Date: 2016-12-02 16:58:10.746677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1300e94cf5cc'
down_revision = '3ee40f5fdc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ndex', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('sp_attack', sa.Integer(), nullable=True),
    sa.Column('sp_defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('type1_id', sa.Integer(), nullable=True),
    sa.Column('type2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type1_id'], ['type.id'], ),
    sa.ForeignKeyConstraint(['type2_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
