"""empty message

Revision ID: 3f740c453801
Revises: 
Create Date: 2016-12-02 16:07:45.315492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f740c453801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type1_id', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('type2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'type', ['type2_id'], ['id'])
    op.create_foreign_key(None, 'pokemon', 'type', ['type1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'type2_id')
    op.drop_column('pokemon', 'type1_id')
    # ### end Alembic commands ###
