"""empty message

Revision ID: 68a3209da638
Revises: b1bf453fa0ad
Create Date: 2016-12-05 16:10:22.069898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a3209da638'
down_revision = 'b1bf453fa0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type1_id', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('type2_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'pokemon_type1_fkey', 'pokemon', type_='foreignkey')
    op.drop_constraint(u'pokemon_type2_fkey', 'pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon', 'type', ['type1_id'], ['id'])
    op.create_foreign_key(None, 'pokemon', 'type', ['type2_id'], ['id'])
    op.drop_column('pokemon', 'type1')
    op.drop_column('pokemon', 'type2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pokemon', sa.Column('type1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.create_foreign_key(u'pokemon_type2_fkey', 'pokemon', 'type', ['type2'], ['id'])
    op.create_foreign_key(u'pokemon_type1_fkey', 'pokemon', 'type', ['type1'], ['id'])
    op.drop_column('pokemon', 'type2_id')
    op.drop_column('pokemon', 'type1_id')
    # ### end Alembic commands ###
