"""empty message

Revision ID: 69c3cd4d770c
Revises: d54ac97c5436
Create Date: 2017-01-04 16:16:08.906080

"""

# revision identifiers, used by Alembic.
revision = '69c3cd4d770c'
down_revision = 'd54ac97c5436'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability1_id', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('ability2_id', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('hidden_ability_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'ability', ['ability1_id'], ['id'])
    op.create_foreign_key(None, 'pokemon', 'ability', ['ability2_id'], ['id'])
    op.create_foreign_key(None, 'pokemon', 'ability', ['hidden_ability_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'hidden_ability_id')
    op.drop_column('pokemon', 'ability2_id')
    op.drop_column('pokemon', 'ability1_id')
    ### end Alembic commands ###
