"""empty message

Revision ID: b1bf453fa0ad
Revises: 1300e94cf5cc
Create Date: 2016-12-05 16:02:57.530887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bf453fa0ad'
down_revision = '1300e94cf5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type1', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('type2', sa.Integer(), nullable=True))
    op.drop_constraint(u'pokemon_type1_id_fkey', 'pokemon', type_='foreignkey')
    op.drop_constraint(u'pokemon_type2_id_fkey', 'pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon', 'type', ['type1'], ['id'])
    op.create_foreign_key(None, 'pokemon', 'type', ['type2'], ['id'])
    op.drop_column('pokemon', 'type2_id')
    op.drop_column('pokemon', 'type1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pokemon', sa.Column('type2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.create_foreign_key(u'pokemon_type2_id_fkey', 'pokemon', 'type', ['type2_id'], ['id'])
    op.create_foreign_key(u'pokemon_type1_id_fkey', 'pokemon', 'type', ['type1_id'], ['id'])
    op.drop_column('pokemon', 'type2')
    op.drop_column('pokemon', 'type1')
    # ### end Alembic commands ###
