"""empty message

Revision ID: c8362e76804f
Revises: 68a3209da638
Create Date: 2016-12-05 18:20:52.104672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8362e76804f'
down_revision = '68a3209da638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('forme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'forme')
    # ### end Alembic commands ###
